version: '3.1'

services:
  broker:
    image: rabbitmq:latest
    ports:
      - '5672:5672'
      - '15672:15672'
  redis-server:
    image: redis:5.0.3
  database:
    image: percona/percona-server:5.7
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    volumes:
      - './infrastructure/data/db/mysql:/var/lib/mysql'

  django-app:
    build: './flight-booking'
    command: gunicorn app.wsgi --bind 0.0.0.0:8000
    restart: always
    ports:
      - '8000:8000'
    environment:
      - DJANGO_MANAGEPY_MIGRATE=on
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_DB_HOST=database
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - DEBUG=${APP_DEBUG}
      - SECRET_KEY=${APP_SECRET_KEY}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - REDIS_URL=${REDIS_URL}
      - CELERY_ACCEPT_CONTENT=${CELERY_ACCEPT_CONTENT}
      - CELERY_TASK_SERIALIZER=${CELERY_TASK_SERIALIZER}
      - CELERY_RESULT_SERIALIZER=${CELERY_RESULT_SERIALIZER}
      - CELERY_TIMEZONE=${CELERY_TIMEZONE}
    depends_on:
      - database
      - broker
      - redis-server

  celery:
    build: './flight-booking'
    command: celery -A app worker -l info
    depends_on:
      - db
      - broker
      - redis-server
  celery-beat:
    build: './flight-booking'
    command: celery -A app beat -l info
    depends_on:
      - db
      - broker
      - redis-server
