version: '3.1'

services:
  broker:
    image: rabbitmq:latest
  redis-server:
    image: redis:5.0.3
  database:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    restart: always
    volumes:
      - './infrastructure/data/db/postgresql:/var/lib/postgresql/data'

  django-app:
    build: './flight-booking'
    # command: gunicorn app.wsgi --bind 0.0.0.0:8000
    command: python manage.py migrate
    restart: always
    ports:
      - '8000:8000'
    environment:
      - DJANGO_MANAGEPY_MIGRATE=on
      - DATABASE_URL={DATABASE_URL}
      - DEBUG=${APP_DEBUG}
      - SECRET_KEY=${APP_SECRET_KEY}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - REDIS_URL=${REDIS_URL}
      - CELERY_ACCEPT_CONTENT=${CELERY_ACCEPT_CONTENT}
      - CELERY_TASK_SERIALIZER=${CELERY_TASK_SERIALIZER}
      - CELERY_RESULT_SERIALIZER=${CELERY_RESULT_SERIALIZER}
      - CELERY_TIMEZONE=${CELERY_TIMEZONE}
    depends_on:
      - database
      - broker
      - redis-server

  celery:
    build:
      context: './flight-booking'
      dockerfile: Dockerfile.worker
    command: celery -A app worker -l info
    depends_on:
      - database
      - broker
      - redis-server
  celery-beat:
    build:
      context: './flight-booking'
      dockerfile: Dockerfile.beat
    command: celery -A app beat -l info
    depends_on:
      - database
      - broker
      - redis-server
