
version: 2
jobs:
  build:
    working_directory: ~/repo/flight-booking
    docker:
      - image: circleci/python:3.7.0
        environment:
          DEBUG: on
          SECRET: $SECRET

    steps:
      - checkout:
          path: ~/repo

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            mkdir -p test-results
            python manage.py test --xunit-file=test-results/xunittest.xml

      - run:
          name: Get Coverage
          command: |
            source venv/bin/activate
            coverage report
            coverage html -d test-results

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
          destination: tr1

