# Generated by Django 2.1.5 on 2019-01-24 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_reminder_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reminder_sent',
            new_name='is_reminder_sent',
        ),
    ]
