# Generated by Django 2.1.3 on 2018-12-30 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_custom_fix_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'permissions': (('update_own_picture', 'Can Update His/Her Profile Picture'), ('delete_own_picture', 'Can remove His/Her Profile Picture'), ('retrieve_own_picture', 'Can View His/Her Profile Picture'), ('retrieve_any_picture', 'Can View Any Profile Picture'), ('update_any_picture', 'Can Update Any Users Profile Picture'), ('delete_any_picture', 'Can remove Any Users Profile Picture'))},
        ),
    ]
