# Generated by Django 2.1.5 on 2019-01-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_custom_fix_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Client'), (1, 'Normal Staff'), (2, 'Super Staff')], default=0),
        ),
    ]
