# Generated by Django 2.1.5 on 2019-01-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accounts_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='passport_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
